networks:
  flink-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  flink-jobmanager:
    build:
      context: ./scripts
      dockerfile: fflink.Dockerfile
    container_name: flink-jobmanager
    hostname: jobmanager
    command: jobmanager
    profiles:
      - servico_extracao_sptans
    ports:
      - "8081:8081"   # Flink Web UI
      - "8083:8083"
    networks:
      flink-net:
        ipv4_address: 172.20.0.10

    environment:
      TZ: America/Sao_Paulo
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
        
        # Habilita o SQL Gateway
        rest.address: jobmanager
        sql-gateway.endpoint.type: rest
        sql-gateway.bind-address: 0.0.0.0
        sql-gateway.bind-port: 8083
    volumes:
      - ./flink/jobs:/opt/flink/jobs

  flink-taskmanager-1:
    build:
      context: ./scripts
      dockerfile: fflink.Dockerfile
    container_name: flink-taskmanager-1
    depends_on:
      - flink-jobmanager
    command: taskmanager
    profiles:
      - servico_extracao_sptans
    networks:
      flink-net:
        ipv4_address: 172.20.0.11
    environment:
      TZ: America/Sao_Paulo
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./flink/jobs:/opt/flink/jobs


  flink-taskmanager-2:
    build:
      context: ./scripts
      dockerfile: fflink.Dockerfile
    container_name: flink-taskmanager-2
    depends_on:
      - flink-jobmanager
    command: taskmanager
    profiles:
      - servico_extracao_sptans
    networks:
      flink-net:
        ipv4_address: 172.20.0.12
    environment:
      TZ: America/Sao_Paulo
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./flink/jobs:/opt/flink/jobs


  flink-sql-client:
    build:
      context: ./scripts
      dockerfile: fflink.Dockerfile
    container_name: flink-sql-client
    profiles:
      - servico_extracao_sptans
    depends_on:
      - flink-jobmanager
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    networks:
      flink-net:
        ipv4_address: 172.20.0.20
    environment:
      TZ: America/Sao_Paulo
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager    
    volumes:
      - ./flink/sql:/opt/flink/sql
      - ./flink/sql:/opt/flink/sql



  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    hostname: kafka
    profiles:
      - servico_kafka
    networks:
      flink-net:
        ipv4_address: 172.20.0.21
    ports:
      - "9092:9092"   # acesso externo (host)
      - "9093:9093"   # controller
      - "29092:29092" # acesso interno (containers)
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CLUSTER_ID: "kafka-cluster-local"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9092,INTERNAL://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - ./kafka_data:/var/lib/kafka/data
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    profiles:
      - servico_kafka
    hostname: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8084:8080"   # UI acessível no navegador
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""  # vazio, pois estamos em KRaft
    networks:
      flink-net:
        ipv4_address: 172.20.0.22
    restart: unless-stopped

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    container_name: schema-registry
    hostname: schema-registry
    profiles:
      - servico_kafka

    depends_on:
      - kafka

    networks:
      flink-net:
        ipv4_address: 172.20.0.23

    ports:
      - "8085:8081"

    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092

    restart: unless-stopped