{
  "namespace": "sptrans",
  "type": "record",
  "name": "BusPosition",
  "fields": [
    {
      "name": "codigo_linha",
      "type": "string"
    },
    {
      "name": "codigo_onibos",
      "type": "string"
    },
    {
      "name": "sentido_operacao",
      "type": "int"
    },
    {
      "name": "letreiro0",
      "type": "str"
    },
    {
      "name": "letreiro1",
      "type": "str"
    },
    {
      "name": "qtd_onibus",
      "type": "int"
    },
    {
      "name": "acessibilidade",
      "type": "bool"
    },
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "latitude",
      "type": "long"
    },
    {
      "name": "longitude",
      "type": "long"
    }
  ]
}